kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "ngshare.name" . }}-pvc
  labels:
    {{- include "ngshare.labels" . | nindent 4 }}
  {{- if .Values.pvc.annotations }}
  annotations:
    {{- .Values.pvc.annotations | toYaml | trimSuffix "\n" | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.pvc.selector }}
  selector:
    {{- .Values.pvc.selector | toYaml | trimSuffix "\n" | nindent 4 }}
  {{- end }}
  {{- if .Values.pvc.storageClassName }}
  storageClassName: {{ .Values.pvc.storageClassName | quote }}
  {{- end }}
  accessModes:
    {{- if eq .Values.deployment.replicaCount 1.0 }}
    - ReadWriteOnce
    {{- else }}
    - ReadWriteMany
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage | quote }}
